# Generated by Django 2.0.1 on 2018-02-23 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='singlefeild',
            options={'verbose_name': 'SF'},
        ),
    ]
