# Generated by Django 2.0.1 on 2018-02-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temp', '0002_auto_20180223_2244'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'MM',
            },
        ),
        migrations.DeleteModel(
            name='SingleFeild',
        ),
    ]
